// t-2: Schwarzschild null-geodesic raytracer (fullscreen fragment integration).
// Photon orbits use the Cartesian light-bending acceleration
// a = -1.5 * h2 * x / r^5 with h2 = |x cross v|^2, rs = 2 * uMass.
// t-3: DISK chunk (volumetric emission/absorption) is prepended to FRAG.
import { DISK } from './disk.js';
// Single source of truth for the galactic band normal: the shader interpolates it
// and the page publishes it in its self-report, so the population the probe samples
// can never drift from the band actually rendered (C3). These are the shipped
// constants; the .toFixed(2) formatting keeps the GLSL literals float-typed and
// bit-identical to the hand-written vec3 they replace.
export const BAND_NORMAL = [0.32, 1.0, 0.24];
export const VERT = [
'void main(){ gl_Position = vec4(position.xy, 0.0, 1.0); }',
].join('\n');

export const FRAG = DISK + [
'precision highp float;',
'uniform vec3 uCamPos; uniform vec3 uCamRight; uniform vec3 uCamUp; uniform vec3 uCamFwd;',
'uniform vec2 uRes; uniform float uMass; uniform float uTime;',
'uniform float uRin; uniform float uRout; uniform int uMarch; uniform float uStarDen; uniform int uDebug;',
'float hash(vec3 p){ return fract(sin(dot(p, vec3(12.9898,78.233,45.164))) * 43758.5453); }',
'vec3 skyColor(vec3 d){',
'  vec3 cell = floor(d * 220.0);',
'  float sThresh = 1.0 - 0.0028 * uStarDen;',
'  float s = step(sThresh, hash(cell));',
'  float tw = 0.55 + 0.45 * sin(uTime * 2.0 + hash(cell + 1.0) * 40.0);',
'  vec3 starCol = mix(vec3(0.7, 0.8, 1.0), vec3(1.0, 0.9, 0.8), hash(cell + 2.0)) * s * tw;',
'  float bandDist = dot(d, normalize(vec3(' + BAND_NORMAL.map((v) => v.toFixed(2)).join(', ') + ')));',
'  float milky = exp(-bandDist * bandDist * 30.0);',
'  float lanes = dFbm(d * 5.0 + vec3(0.0, uTime * 0.004, 0.0));',
'  vec3 galaxy = milky * (vec3(0.18, 0.22, 0.33) * (0.10 + 0.75 * lanes));',
'  float glow = exp(-bandDist * bandDist * 8.0) * 0.06;',
'  return starCol * 0.9 + galaxy + vec3(0.20, 0.24, 0.34) * glow;',
'}',
'void main(){',
'  vec2 ndc = (gl_FragCoord.xy / uRes) * 2.0 - 1.0; ndc.x *= uRes.x / uRes.y;',
'  float rs = 2.0 * uMass; float rIn = uRin * uMass; float rOut = uRout * uMass;',
'  vec3 diskCol = vec3(0.0); float transmit = 1.0;',
'  float dbgRho = 0.0; float dbgT = 0.0; float dbgDop = 1.0; float dbgGrs = 1.0;',
'  vec3 x = uCamPos;',
'  vec3 v = normalize(uCamFwd + ndc.x * uCamRight + ndc.y * uCamUp);',
'  float h2 = dot(cross(x, v), cross(x, v));',
'  float captured = 0.0; float bent = 0.0; float crossCount = 0.0; float minR = 1e9;',
'  float prevY = x.y;',
'  for (int i = 0; i < 256; i++) {',
'    if (i >= uMarch) { break; }',
'    float r = length(x); minR = min(minR, r);',
'    if (r < rs) { captured = 1.0; break; }',
'    if (r > 60.0 && dot(x, v) > 0.0) { break; }',
'    vec3 bendAcc = -1.5 * h2 * x / pow(max(r, 1e-3), 5.0);',
'    bent += length(bendAcc);',
'    float dt = 0.12 * max(r - rs * 0.9, 0.05);',
'    v = normalize(v + bendAcc * dt); x += v * dt;',
'    float diskR = length(x.xz);',
'    if (prevY * x.y < 0.0 && diskR > rIn && diskR < rOut) { crossCount += 1.0; }',
'    float rho = diskDensity(x, rIn, rOut, uTime);',
'    if (rho > 0.004 && transmit > 0.01) {',
'      float rr = length(x);',
'      float T = diskTemperature(rr, rIn);',
'      float dop = dopplerBeam(v, diskVelocity(x));',
'      float grs = gravityRedshift(rr, rs);',
'      // Kirchhoff-coupled transport: ONE coefficient drives emission AND absorption, with',
'      // the path element measured per unit scale height. The shipped 2.4-emits against',
'      // 1.6-absorbes split decoupled them, which made the path integral supremum',
'      // (2.4/1.6)*colMax(T)*dop = 7.27 linear at rIn and 2.56 at rOut -- above the clip',
'      // ceiling at every radius the disk occupies. One coefficient now bounds it by the',
'      // source function. kappa is opacity per unit SCALE HEIGHT, so tau is a column',
'      // density measured in disk thicknesses rather than raw steps; 0.02 keeps the',
'      // midplane optically THIN (tau ~ 0.35), the regime a visible VOLUMETRIC disk',
'      // describes, and holds the emergent radiance under the 0.82 bloom threshold so the',
'      // pass cannot run away. Measured, not assumed: canvas mean 224.7 at kappa 1.6 and',
'      // 134.4 at kappa 0.05, both above the arm bound, so brightness keeps coming from',
'      // (1 - e^-tau) rather than from any gain applied near the tone curve.',
'      float ds = dt / max(scaleHeight(diskR), 1e-3);',
'      float dtau = 0.04 * rho * ds;',
'      diskCol += transmit * diskTint(T) * dtau * dop * grs;',
'      transmit *= exp(-dtau);',
'      dbgRho = rho; dbgT = T; dbgDop = dop; dbgGrs = grs;',
'    }',
'    prevY = x.y;',
'  }',
'  float ring = exp(-pow((minR - 1.5 * rs) / (0.07 * rs), 2.0));',
'  vec3 col = (skyColor(normalize(v)) + vec3(1.0, 0.95, 0.85) * ring * 1.1) * transmit * (1.0 - captured);',
'  col += diskCol;',
'  if (uDebug == 1) { col = vec3(clamp(bent * 0.02, 0.0, 1.5)); }',
'  else if (uDebug == 2) { col = vec3(captured); }',
'  else if (uDebug == 3) { col = vec3(1.0, 0.95, 0.85) * ring * 2.0; }',
'  else if (uDebug == 4) { col = vec3(dbgRho * 2.0, dbgRho, dbgRho * 0.5); }',
'  else if (uDebug == 5) { col = temperatureColor(dbgT); }',
'  else if (uDebug == 6) { col = vec3(dbgDop * 0.5); }',
'  else if (uDebug == 7) { col = vec3(dbgGrs); }',
'  else if (uDebug == 8) { col = skyColor(normalize(v)); }',
'  // view 9 shows the ABSORBED fraction 1 - transmit = 1 - e^-tau, the optical-depth',
'  // structure the volumetric march computes. Raw transmit is ~1 everywhere now that',
'  // tau is thin by design, so it rendered the same near-unity field as the g^4 that',
'  // view 7 prints (per-view means 251.79 vs 250.75), and X1 could not separate them.',
'  else if (uDebug == 9) { col = vec3(1.0 - transmit); }',
'  gl_FragColor = vec4(col, 1.0);',
'}',
].join('\n');
